### ISSUE TITLE
feat: add ellipsis for readonly-form-field-wrapper

### ISSUE THREAD

**Issue by peter-varga-sp** [porscheinformatik/material-addons#59]
# Feature request

It should be possible to add Ellipsis feature to the mad-readonly-form-field-wrapper component. 

## Description

Currently, if the text is too long to be shown in the field, it gets just truncated. With Ellipsis, in this case three dots should be shown at the right side of the field, and a toolbar should show the whole value, by mouse over. 

## Possible Solution

Add style "text-overflow: ellipsis" the input element of  mad-readonly-form-field-wrapper component.

**Comment by Laess3r** [comment]
Implemented with #62
