### ISSUE TITLE
feat: [DataTable] Batch Action - Example

### ISSUE THREAD

**Issue by d-m-s** [porscheinformatik/material-addons#74]
# Feature request
**[DataTable] Batch Action - Example**
 - selection
 - selection-counter in datagrid-footer
 - contextual actions: delete is only active when 1-n rows are selected

# Description
Provide living styleguide example of batch-action datagrid pattern.
- add = independent from selection
- edit= 1 row must be selected
- delete = 1-n rows must be selected
- select-all = should select the current page-size

# Out of focus
- export should be omitted in this example
- column settings should be omitted in this example

# XD Prototyp
https://xd.adobe.com/view/d9d7657d-7873-4f87-a653-af6c2c61f2c1-8c84/

**Comment by Sylvain-Wehrum** [comment]
done in version 10.3.0
